window.siteLintPages = [
  { value: "https://docs.google.com/spreadsheets/d/1p4zejQ4g_Hfiz_ine9-EwUppILYmX9msd9SwGlHSvgA/edit?gid=863730017#gid=863730017", label: "View the SiteLint Google spreadsheet", target: "_blank" },
  { value: "https://www.sitelint.com/docs/accessibility", label: "View the full list of SiteLint rules", target: "_blank" },
  { value: "https://sitelint-testing.github.io/axe-dev-tools/", label: "Switch to the axe Dev Tools testing suite", target: "_blank" },
  { value: "https://sitelint-testing.github.io/arc-toolkit/", label: "Switch to the ARC Toolkit testing suite", target: "_blank" },
  { value: "accessible-name-mismatch-element-description.html", label: "1. accessible name mismatch element description" },
  { value: "accessible-name-pm1097.html", label: "2. Accessible Name - PM-1097 - BOA logos" },
  { value: "alt-color-convey-information.html", label: "3. alt color convey information" },
  { value: "alt-text-filename.html", label: "4. alt text filename" },
  { value: "animation.html", label: "5. animation" },
  { value: "applet-missing-alt.html", label: "6. applet missing alt" },
  { value: "applet-missing-body.html", label: "7. applet missing body" },
  { value: "autocomplete-attribute-usage.html", label: "8. autocomplete attribute usage" },
  { value: "area-missing-alt.html", label: "9. area missing alt" },
  { value: "aria-attribute-conflict.html", label: "10. aria attribute conflict" },
  { value: "aria-describedby-association.html", label: "11. aria-describedby association" },
  { value: "aria-hidden-false.html", label: "12. aria hidden false" },
  { value: "aria-hidden-true-focusable-descendants.html", label: "13. aria hidden true focusable descendants" },
  { value: "aria-labelledby-association-empty-element.html", label: "14. aria-labelledby association empty element" },
  { value: "aria-labelledby-association.html", label: "15. aria-labelledby association" },
  { value: "aria-role-dialog.html", label: "16. aria role dialog" },
  { value: "audio-alternative.html", label: "17. audio alternative" },
  { value: "audio-video-captions.html", label: "18. audio video captions" },
  { value: "autoplay-audio-video.html", label: "19. autoplay audio video" },
  { value: "blink-element.html", label: "20. blink element" },
  { value: "broken-same-page-link.html", label: "21. broken same page link" },
  { value: "capital-letters.html", label: "22. capital letters" },
  { value: "captcha-google.html", label: "23. captcha google" },
  { value: "click-verb.html", label: "24. click verb" },
  { value: "color-contrast-aa.html", label: "25. color contrast aa" },
  { value: "color-contrast-aaa.html", label: "26. color contrast aaa" },
  { value: "color-contrast-state-pseudo-classes.html", label: "27. color contrast state pseudo classes" },
  { value: "color-name.html", label: "28. color name" },
  { value: "content-editable-missing-attributes.html", label: "29. content editable missing attributes" },
  { value: "content-wider-than-screen.html", label: "30. content wider than screen" },
  { value: "contentinfo-landmark-only-one.html", label: "31. contentinfo landmark only one" },
  { value: "css-images-convey-information.html", label: "32. css images convey information" },
  { value: "dynamic.html", label: "33. Dynamic Content" },
  { value: "duplicated-for-attribute.html", label: "34. duplicated for attribute" },
  { value: "duplicated-id.html", label: "35. duplicated id" },
  { value: "ebi-test.html", label: "36. ebi test" },
  { value: "empty-button-description.html", label: "37. empty button description" },
  { value: "empty-heading.html", label: "38. empty heading" },
  { value: "empty-label-element.html", label: "39. empty label element" },
  { value: "empty-link-element.html", label: "40. empty link element" },
  { value: "empty-title-attribute.html", label: "41. empty title attribute" },
  { value: "fieldset-no-legend.html", label: "42. fieldset no legend" },
  { value: "flash-content.html", label: "43. flash content" },
  { value: "font-style-italic.html", label: "44. font style italic" },
  { value: "general-alt.html", label: "45. general alt" },
  { value: "group-elements-name-attribute.html", label: "46. group elements name attribute" },
  { value: "h1-must-be-defined.html", label: "47. h1 must be defined" },
  { value: "h1-only-one.html", label: "48. h1 only one" },
  { value: "headings-hierarchy.html", label: "49. headings hierarchy" },
  { value: "headings-sibling-unique.html", label: "50. headings sibling unique" },
  { value: "horizontal-rule.html", label: "51. horizontal rule" },
  { value: "html-lang-attr.html", label: "52. html lang attr" },
  { value: "identify-input-purpose.html", label: "53. identify input purpose" },
  { value: "img-adjacent-duplicate-text-link.html", label: "54. img adjacent duplicate text link" },
  { value: "img-alt-duplicate-text-link.html", label: "55. img alt duplicate text link" },
  { value: "img-empty-alt-in-link.html", label: "56. img empty alt in link" },
  { value: "img-empty-alt-with-empty-title.html", label: "57. img empty alt with empty title" },
  { value: "inaccessible-svg.html", label: "58. inaccessible svg" },
  { value: "incorrect-label-placement-for-associated-input.html", label: "59. incorrect label placement for associated input" },
  { value: "incorrect-technique-for-hiding-content.html", label: "60. incorrect technique for hiding content" },
  { value: "input-image-missing-alt.html", label: "61. input image missing alt" },
  { value: "invalid-attribute-dir-value.html", label: "62. invalid attribute dir value" },
  { value: "label-duplicated-content-title.html", label: "63. label duplicated content title" },
  { value: "label-implicitly-associated.html", label: "64. label implicitly associated" },
  { value: "label-inappropriate-association.html", label: "65. label inappropriate association" },
  { value: "label-visually-hidden-only.html", label: "66. label visually hidden only" },
  { value: "legend-first-child-of-fieldset.html", label: "67. legend first child of fieldset" },
  { value: "link-button-space-key.html", label: "68. link button space key" },
  { value: "link-with-unclear-purpose.html", label: "69. link with unclear purpose" },
  { value: "links-language-destination.html", label: "70. links language destination" },
  { value: "links-new-window-mark.html", label: "71. links new window mark" },
  { value: "links-not-visually-evident-without-color-vision.html", label: "72. links not visually evident without color vision" },
  { value: "links-same-content-different-url.html", label: "73. links same content different url" },
  { value: "main-element-only-one.html", label: "74. main element only one" },
  { value: "main-landmark-must-be-top-level.html", label: "75. main landmark must be top level" },
  { value: "manifest-extension.html", label: "76. manifest extension" },
  { value: "minimum-font-size.html", label: "77. minimum font size" },
  { value: "missing-alt-attribute.html", label: "78. missing alt attribute" },
  { value: "missing-href.html", label: "79. missing href" },
  { value: "missing-label.html", label: "80. missing label" },
  { value: "missing-submit-button.html", label: "81. missing submit button" },
  { value: "misused-aria.html", label: "82. misused aria" },
  { value: "misused-input-attribute.html", label: "83. misused input attribute" },
  { value: "misused-required-attribute.html", label: "84. misused required attribute" },
  { value: "misused-tabindex-attribute.html", label: "85. misused tabindex attribute" },
  { value: "navigation-landmark-restrictions.html", label: "86. navigation landmark restrictions" },
  { value: "no-headings.html", label: "87. no headings" },
  { value: "no-meta-http-equiv-refresh.html", label: "88. no meta http-equiv refresh" },
  { value: "object-general-alt.html", label: "89. object general alt" },
  { value: "object-missing-body.html", label: "90. object missing body" },
  { value: "obsolete-html-attributes.html", label: "91. obsolete html attributes" },
  { value: "obsolete-html-elements.html", label: "92. obsolete html elements" },
  { value: "orientation.html", label: "93. orientation" },
  { value: "outline-zero.html", label: "94. outline zero" },
  { value: "overlay.html", label: "95. overlay" },
  { value: "position-sticky.html", label: "96. position sticky" },
  { value: "positive-tabindex.html", label: "97. positive tabindex" },
  { value: "reflow.html", label: "98. reflow" },
  { value: "role-application.html", label: "99. role application" },
  { value: "rtl-content.html", label: "100. rtl content" },
  { value: "same-target-anchor-text-more-than-once.html", label: "101. same target anchor text more than once" },
  { value: "svg-without-accessible-description.html", label: "102. svg without accessible description" },
  { value: "table-caption-summary-identical.html", label: "103. table caption summary identical" },
  { value: "table-missing-description.html", label: "104. table missing description" },
  { value: "table-row-and-column-headers.html", label: "105. table row and column headers" },
  { value: "target-size-minimum.html", label: "106. target size minimum" },
  { value: "text-color-convey-information.html", label: "107. text color convey information" },
  { value: "contrast-ratios.html", label: "108. Text size, style and contrast ratios" },
  { value: "title-for-abbr.html", label: "109. title for abbr" },
  { value: "title-iframe.html", label: "110. title iframe" },
  { value: "unclear-anchor-url.html", label: "111. unclear anchor url" },
  { value: "unclear-image-description.html", label: "112. unclear image description" },
  { value: "unclear-page-title.html", label: "113. unclear page title" },
  { value: "unsupported-role-on-element.html", label: "114. unsupported role on element" },
  { value: "video-audio-descriptions.html", label: "115. video audio descriptions" },
  { value: "zoom-disabled.html", label: "116. zoom disabled" },
  { value: "99problems.html", label: "117. 99 Problems" },
  { value: "multiple-languages.html", label: "118. multiple languages" }
];